# config/routes.yaml

# Import all controllers with PHP attributes
controllers:
    resource: '../src/Controller/'
    type: attribute
    # Permet à Symfony de gérer les trailing slash automatiquement
    trailing_slash_on_root: false